name = "schedule-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "schedule-db"
database_id = "02f839f2-22b4-4da1-aeac-419af3ed826f"
